import turtle
turtle.bgcolor("silver")
turtle.speed(10)
turtle.turtlesize(0.5)
turtle.shape("arrow")
turtle.color("crimson")
turtle.width(2)
for i in range(10, 1000, 10):
    turtle.forward(i)
    turtle.left(90)
    turtle.forward(i)
    turtle.left(90)
    turtle.forward(i)
    turtle.left(90)
    turtle.forward(i)
    turtle.left(45)
    turtle.penup()
    turtle.forward(i%10)
    turtle.pendown()
turtle.exitonclick()