import turtle
turtle.penup()
turtle.width(3)
turtle.setpos(0,-10)
turtle.shape("turtle")
turtle.color("olive")
turtle.pendown()
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()
turtle.exitonclick()